package com.controller;

import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.commons.fileupload.FileItem;
import org.apache.commons.fileupload.disk.DiskFileItemFactory;
import org.apache.commons.fileupload.servlet.ServletFileUpload;

import com.beans.Doctor;
import com.model.Account;

public class DocRegistration extends HttpServlet {
	private static final long serialVersionUID = 1L;
	private final String dir="C:/Users/Aditya/Desktop/AdiJ2EE/ehealth/WebContent/uploads";
	
	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		String action=request.getParameter("action");
		if(action==null){
			 request.setAttribute("msg"," ");
			 request.setAttribute("msg1","");
			 request.setAttribute("msg2","");
			 request.setAttribute("msg3","");
			 request.setAttribute("msg4","");
			 request.setAttribute("msg5","");
			 request.setAttribute("msg6","");
			 request.setAttribute("message", "");
			request.getRequestDispatcher("jsps/docregistration/index.jsp").forward(request, response);
		}else{
			doPost(request, response);
		}
	}


	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		String action=request.getParameter("action");
		if(action.equals("register_doc")){
			
			Doctor doc=new Doctor();
		
			String nam=request.getParameter("nam");
			String degree=request.getParameter("degree");
			String email=request.getParameter("email");
			String password=request.getParameter("password");
			String repassword=request.getParameter("repassword");
			String category=request.getParameter("category");
			String contact=request.getParameter("contact");
			String code=request.getParameter("code");
			String captcha=(String)request.getSession().getAttribute("captcha");//Code generated by CaptchaServlet
			
			doc.setEmail(email);
			doc.setNam(nam);
			doc.setDegree(degree);
				doc.setPassword(password);
				doc.setRepassword(repassword);
				doc.setContact(contact);
			doc.setCategory(category);
				
			boolean status=doc.validate();

			if(status==true && code.equals(captcha)){
				Account a=new Account();
			try {
				a.insertDocdb(nam,email,password,degree,contact,category);
			} catch (ClassNotFoundException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			request.setAttribute("msg", "Registration Successful,Now Login using same email & Password");
			request.getRequestDispatcher("jsps/main/index.jsp").forward(request, response);
						
		}else{
			
			request.setAttribute("msg", "Registration UNSuccessful");
			request.setAttribute("msg1",doc.msg1);
			 request.setAttribute("msg2",doc.msg2);
			 request.setAttribute("msg3",doc.msg3);
			 request.setAttribute("msg4",doc.msg4);
			 request.setAttribute("msg5",doc.msg5);
			 request.setAttribute("msg6",doc.msg6);
			 request.setAttribute("msg8",doc.msg8);
			 request.setAttribute("msg7", "Captcha Invalid");
			
			
			 request.getRequestDispatcher("jsps/docregistration/index.jsp").forward(request, response);
			}
		

	}
		if(action.equals("file-upload")){
			String name="";
			if(ServletFileUpload.isMultipartContent(request)){
		            try {
		                List<FileItem> multiparts = new ServletFileUpload(
		                                         new DiskFileItemFactory()).parseRequest(request);
		              
		                for(FileItem item : multiparts){
		                    if(!item.isFormField()){
		                        name = new File(item.getName()).getName();
		                        String[] ext=name.split("\\.");
		                        if(ext[1].equals("jpg")||ext[1].equals("jpeg")){
		                        item.write( new File(dir+ File.separator + name));
		                        request.setAttribute("name",name);
		                        request.setAttribute("message", "Profile Picture Uploaded Successfully");
		                        request.getRequestDispatcher("jsps/login/login_doc.jsp").forward(request, response);	 
		                    }else{
		                    	 request.setAttribute("message", "Sorry,We take only jpeg or jpg");
		                    	 request.getRequestDispatcher("jsps/docregistration/upload.jsp").forward(request, response);	
		                    }
		                        
		                }}
		           
		               //File uploaded successfully
		               
		            } catch (Exception ex) {
		               request.setAttribute("message", "File Upload Failed due to " + ex);
		               request.getRequestDispatcher("jsps/docregistration/upload.jsp").forward(request, response);	

		            }          
		         
		        }else{
		            request.setAttribute("message",
		                                 "Sorry this Servlet only handles file upload request");
		        }
			
			
			
			
			}	
		}
		
}
		
				
