package com.controller;

import java.io.IOException;
import java.sql.SQLException;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.beans.User;
import com.model.Account;

/**
 * Servlet implementation class Registration
 */
public class Registration extends HttpServlet {
	private static final long serialVersionUID = 1L;

	
	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		String action=request.getParameter("action");
		 if(action==null){
			 request.setAttribute("msg"," ");
			 request.setAttribute("msg1","");
			 request.setAttribute("msg2","");
			 request.setAttribute("msg3","");
			 request.setAttribute("msg4","");
			 request.getRequestDispatcher("jsps/registration/index.jsp").forward(request, response);
	} else{
		doPost(request,response);
	}
	}

	
	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		String action=request.getParameter("action");//
		User user = new User();
		if(action.equals("register_user")){
			String name=request.getParameter("name");
			String email=request.getParameter("email");
			String password=request.getParameter("password");
			String repassword=request.getParameter("repassword");
			String code=request.getParameter("code");
			String captcha=(String)request.getSession().getAttribute("captcha");//Code generated by CaptchaServlet

		    user.setEmail(email);
			user.setName(name);
			user.setPassword(password);
			user.setRepassword(repassword);

			boolean status=user.validate();
		
			
			if(status==true && code.equals(captcha)){
				

				Account a=new Account();
			try {
				a.insert(name,email,password);
			} catch (ClassNotFoundException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			request.setAttribute("msg", "Registration Successful,Now Login using same email & Password");
			request.getRequestDispatcher("jsps/login/login_user.jsp").forward(request, response);
						
		}else{
			
			request.setAttribute("msg", "Registration UNSuccessful");
			request.setAttribute("msg1",user.msg1);
			 request.setAttribute("msg2",user.msg2);
			 request.setAttribute("msg3",user.msg3);
			 request.setAttribute("msg4",user.msg4);
			 request.setAttribute("msg5", "Captcha Invalid");
			
			
			 request.getRequestDispatcher("jsps/registration/index.jsp").forward(request, response);
			}
		
}
	}
}